export const countries = [
  { key: "spain", value: "Spain" },
  { key: "france", value: "France" },
  { key: "germany", value: "Germany" },
  { key: "italy", value: "Italy" },
  { key: "portugal", value: "Portugal" },
  { key: "netherlands", value: "Netherlands" },
  { key: "belgium", value: "Belgium" },
  { key: "switzerland", value: "Switzerland" },
  { key: "austria", value: "Austria" },
  { key: "sweden", value: "Sweden" },
  { key: "norway", value: "Norway" },
  { key: "denmark", value: "Denmark" },
  { key: "finland", value: "Finland" },
  { key: "ireland", value: "Ireland" },
  { key: "united_kingdom", value: "United Kingdom" },
  { key: "greece", value: "Greece" },
  { key: "turkey", value: "Turkey" },
  { key: "russia", value: "Russia" },
  { key: "poland", value: "Poland" },
  { key: "czech_republic", value: "Czech Republic" },
  { key: "hungary", value: "Hungary" },
  { key: "romania", value: "Romania" },
  { key: "bulgaria", value: "Bulgaria" },
  { key: "croatia", value: "Croatia" },
  { key: "serbia", value: "Serbia" },
  { key: "slovakia", value: "Slovakia" },
  { key: "slovenia", value: "Slovenia" },
  { key: "estonia", value: "Estonia" },
  { key: "latvia", value: "Latvia" },
  { key: "lithuania", value: "Lithuania" },
];
