export type Inputs = {
  name: string;
  password: string;
  nickname: string;
  sex: string;
  photo: { file: File; width: number; height: number } | null;
  birth: string;
  age: string;
  weightClass: string;
  weightClassOption: string;
  weightClassOption2: string;
  weightClass2: string;
  weightClass3: string;
  gim: string;
  nationality: string;
  based: string;
  professionalRecord: string;
  amateurRecord: string;
  foundation: string;
  topology: string;
  sherdog: string;
  socials: string;
  about: string;
  isAgree: boolean;
  management: string;
  email: string;
  isFighter: boolean;
  social: string;
  confirmEmail: string;
  phone: string;
  confirmPassword: string;
  place: string;
  promotions: string;
  rules: string;
  weight: string;
};
