import type { Metadata } from "next";
import "./globals.scss";
import { roboto } from "./ui/fonts";
import Header from "./layout/Header/Header";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased`}>
        <Header />
        <main>{children}</main>
        <div id="portal"></div>
      </body>
    </html>
  );
}
