import type { Metadata } from "next";
import "./globals.scss";
import { roboto } from "./ui/fonts";
import Providers from "./Providers/Providers";
import Modal from "./components/Modal/Modal";
import Header from "./layout/Header";
import Footer from "./layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased text-sm`}>
        <Providers>
          <Header />
          <Modal />
          <main>{children}</main>
          <div id="portal"></div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
