import type { Metadata } from "next";
import "../globals.scss";
import Providers from "../components/Providers/Providers";
import { roboto } from "../components/ui/fonts";
import Header from "../components/layout/Header";
import Modal from "../components/Modal/Modal";
import Footer from "../components/layout/Footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.className} antialiased text-sm`}>
        <Providers>
          <Header />
          <Modal />
          <main className="min-h-[90dvh]">{children}</main>
          <div id="portal"></div>
          <Footer />
        </Providers>
      </body>
    </html>
  );
}
